### ISSUE TITLE
Add Sass Source Maps

### ISSUE THREAD

**Issue by Misplon** [siteorigin/theme-build#10]
@braamgenis Do you think we can add Sass source maps to the dev build process?

http://thesassway.com/intermediate/using-source-maps-with-sass

It would be super helpful. Especially when jumping back into a theme you haven't been actively working on.

**Comment by braamgenis** [comment]
Cool, done [here](2f834268239796540c0ece0747dbd8624b6121ad).

Just update your build repo and run `npm install`, then running a `build:dev` will generate the sourcemaps and put them in `sass/maps`.

**Comment by Misplon** [comment]
So awesome man, will check it out shortly. Thanks :)
