### ISSUE TITLE
Add CSS minification

### ISSUE THREAD

**Issue by Misplon** [siteorigin/theme-build#12]
Hey @braamgenis. .org allows us to use minified CSS files if we include the unminified version, just as we do with JS files. Add minification would help all of our users that don't use performance plugins.

Task: Add CSS minification to the build in exactly the same way that we're currently handling JS min.

Add a new constant:

`define( 'SITEORIGIN_THEME_CSS_PREFIX', '' );`

We'll then change the theme CSS enqueue to:

`wp_enqueue_style( 'siteorigin-unwind-style', get_template_directory_uri() . '/style' . SITEORIGIN_THEME_CSS_PREFIX . '.css', array(), SITEORIGIN_THEME_VERSION );`

In the `build:dev` task we'll use the unminifed version and in the `build:release` task we'll use the minified version.

An additional task is doing the same for other CSS files. For example, in North we have https://github.com/siteorigin/siteorigin-north/blob/develop/css/north-icons.css. The same process should ideally be run on this file too.

Let me know if you'd like to run over any of these points. Cheers :)

**Comment by braamgenis** [comment]
Done in 98c68672c7d8976bc0c7533a84637e56b668ec1e. See d86620fedbc8739789295a43d0a316584de03458 in Unwind for example usage. As usual, you'll have to update the `build` submodule in each theme you want to use it in.
