### ISSUE TITLE
Add livereload for Js files

### ISSUE THREAD

**Issue by Misplon** [siteorigin/theme-build#13]
If possible, add livereload for JS files.

**Comment by braamgenis** [comment]
Done here 45877edd47aa62b53ffc72b4644933db1ef80f3f

**Comment by adiraomj** [comment]
The page reloads, but the file does not get updated..

@Misplon are you seeing this too?

**Comment by Misplon** [comment]
Seems to be updating for me. Can you let me know the theme and perhaps give me a snippet to try out?
