### ISSUE TITLE
Release version number isn't printing in style.css or style.min.css

### ISSUE THREAD

**Issue by Misplon** [siteorigin/theme-build#15]
Hey @braamgenis. I can't seem to get the version number to print in style.css or style.min.css for the release task. Could you perhaps, take a look?

**Comment by braamgenis** [comment]
Fixed in 751e616a8bcffe628e7b6902d8ef7c99c986ba63.

**Comment by Misplon** [comment]
Legend, thanks dude. We've got the CSS version number issued dialled in now. However, it looks like we're no longer printing the version number and suffixes (.min) to the constants at the top of the `functions.php` file. Can you check to see if you're seeing the same issue?

**Comment by braamgenis** [comment]
OK, hopefully that's really fixed now. :sweat_smile:

**Comment by Misplon** [comment]
Perfect :)
