### ISSUE TITLE
Expand CSS min for files in sub-folders

### ISSUE THREAD

**Issue by Misplon** [siteorigin/theme-build#16]
@braamgenis Would it be possible to expand CSS minification to files in sub-folders. Here is our config:

```
    css: {
        src: [
            'style.css',
            'woocommerce.css',
            'woocommerce-rtl.css',
            'woocommerce-smallscreen-rtl.css',
            'css/flexslider.css',
            'css/north-icons.css',
        ],
    },
```

It doesn't seem to be outputting the files in the css folder but did so in earlier iterations of the build CSS minification. Thanks man.

**Comment by braamgenis** [comment]
Hope that does it.
