### ISSUE TITLE
Option to have contributors.php instead of contributors.json.

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/theme-build#6]
If we want to use contributors.json in the theme, we'll need to make use of the WordPress filesystem, which is sometimes not available. To get through the review queue, themes also can't use `file_get_contents` which would make working with the json file easier.

So there should be a config option that allows us to convert the contributors file into a php file instead. Something along the lines of 

```
return json_decode( 'JSON CONTENT', true );
```

That way we could just have `$contributors = include get_template_directory() . '/contributors.php';` in our code, which is legal by the theme review guidelines.

**Comment by braamgenis** [comment]
Implemented here 8e0e0821c49024edbd21bd86bf8c8bb6236154ca
